### En un Notebook como este podríamos analizar los servicios de cada cliente, cuál genera más beneficios, y cualquier característica de interés.

In [37]:
from pathlib import Path
import pandas as pd

csvs = list(Path.glob(Path.cwd(), 'csvs/*.csv'))
dfs = [(pd.read_csv(f, parse_dates=['Fecha']), f.name) for f in csvs]

In [38]:
for df, nombre in dfs:
    print(nombre + ':')
    display(df)

juan-5-2026.csv:

       Fecha Concepto  Importe
0 2023-02-12  Nº 1234    76.34
1 2026-12-24  Nº 2315   105.55

pepe-sl.-6-2026.csv:

       Fecha Concepto  Importe
0 2025-06-15  Nº 2315   123.33
1 2026-05-24  Nº 1234    40.20

In [39]:
df_completo = pd.DataFrame()
for df, nombre in dfs:
    df['Cliente'] = nombre.split('-')[0]
    df_completo = pd.concat([df_completo, df])
df_completo

       Fecha Concepto  Importe Cliente
0 2023-02-12  Nº 1234    76.34    juan
1 2026-12-24  Nº 2315   105.55    juan
0 2025-06-15  Nº 2315   123.33    pepe
1 2026-05-24  Nº 1234    40.20    pepe

In [45]:
df_completo.groupby('Concepto')[['Importe']].sum()

          Importe
Concepto
Nº 1234    116.54
Nº 2315    228.88

In [46]:
df_completo.groupby('Cliente')[['Importe']].sum()

         Importe
Cliente
juan      181.89
pepe      163.53